### PR TITLE
1차 완

### PR DESCRIPTION
**Pull request by co-troll**

### CODE REVIEW

**Review by co-troll — COMMENTED** [review]
good

**Review by joonghyeondevelop — APPROVED** [review]
good

**Review by joonghyeondevelop — COMMENTED** [review]
good

**Review by joonghyeondevelop — APPROVED** [review]
goodgood

**Review by joonghyeondevelop — APPROVED** [review]
goodgoodgood

**Review by joonghyeondevelop — APPROVED** [review]
goodgoodgoodgood

**Review by joonghyeondevelop — CHANGES_REQUESTED** [review]
asdasdsad

**Review by joonghyeondevelop — APPROVED** [review]
asdasdsadas

**Review by joonghyeondevelop — COMMENTED** [review]
123123

**Review by joonghyeondevelop — CHANGES_REQUESTED** [review]
wxwxxwwxwx

**Comment by joonghyeondevelop** [comment]
dsgasdgasdg

**Comment by co-troll** [comment]
ㄴㅇㅁㄹ

**Pull request closed without merging**
